package dev.webshield.core;
import dev.webshield.api.*;import java.nio.file.Path;import java.time.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;
public final class DefenseEngine implements WebDefensePlugin{
 private static final class ClientState{double tokens;long lastNanos;final ArrayDeque<Long>usage=new ArrayDeque<>();int violations;long blockedUntil;ClientState(double t){tokens=t;lastNanos=System.nanoTime();}}
 private final Path configPath;private volatile Config cfg;private volatile IpPolicy policy;private volatile JsonAuditLogger logger;private final ConcurrentHashMap<String,ClientState>states=new ConcurrentHashMap<>();private final LongAdder total=new LongAdder(),allowed=new LongAdder(),denied=new LongAdder(),blacklisted=new LongAdder(),rate=new LongAdder(),quota=new LongAdder(),surgeDenied=new LongAdder();
 private final AtomicLong second=new AtomicLong();private final AtomicLong currentCount=new AtomicLong();private volatile double currentRps,baselineRps=1;private volatile long surgeUntil;
 public DefenseEngine(Path configPath){this.configPath=configPath;cfg=Config.load(configPath);policy=new IpPolicy(cfg);logger=new JsonAuditLogger(cfg.logFile());}
 public Decision inspect(WebRequest r){total.increment();rollSecond();String ip=normalize(r.clientIp());long now=System.currentTimeMillis();boolean surge=now<surgeUntil;Decision d;if(policy.allowed(ip)){d=Decision.allow(Long.MAX_VALUE,surge);}else if(policy.denied(ip)){blacklisted.increment();d=Decision.deny("BLACKLIST",cfg.temporaryBlock().toSeconds(),surge);}else{ClientState s=states.computeIfAbsent(ip,k->new ClientState(cfg.burstCapacity()));synchronized(s){if(s.blockedUntil>now)d=Decision.deny("TEMPORARY_BLOCK",(s.blockedUntil-now+999)/1000,surge);else{refill(s);trim(s.usage,now-cfg.rollingWindow().toMillis());if(s.usage.size()>=cfg.rollingQuota()){quota.increment();d=violate(s,"ROLLING_QUOTA",cfg.cooldown().toSeconds(),surge,now);}else{double cost=surge?3.0:1.0;if(s.tokens<cost){if(surge)surgeDenied.increment();else rate.increment();d=violate(s,surge?"SURGE_LIMIT":"RATE_LIMIT",Math.max(1,(long)Math.ceil((cost-s.tokens)/Math.max(.01,cfg.refillPerSecond()))),surge,now);}else{s.tokens-=cost;s.usage.addLast(now);s.violations=Math.max(0,s.violations-1);d=Decision.allow(cfg.rollingQuota()-s.usage.size(),surge);}}}}}if(d.allowed())allowed.increment();else denied.increment();logger.log(r,d);return d;}
 private Decision violate(ClientState s,String reason,long retry,boolean surge,long now){if(++s.violations>=cfg.violationThreshold()){s.blockedUntil=now+cfg.temporaryBlock().toMillis();s.violations=0;return Decision.deny("TEMPORARY_BLOCK",cfg.temporaryBlock().toSeconds(),surge);}return Decision.deny(reason,retry,surge);}
 private void refill(ClientState s){long n=System.nanoTime();double dt=(n-s.lastNanos)/1_000_000_000.0;s.tokens=Math.min(cfg.burstCapacity(),s.tokens+dt*cfg.refillPerSecond());s.lastNanos=n;}
 private void rollSecond(){long sec=System.currentTimeMillis()/1000,prev=second.get();if(prev==0){second.compareAndSet(0,sec);currentCount.incrementAndGet();return;}if(sec==prev){currentCount.incrementAndGet();return;}if(second.compareAndSet(prev,sec)){long count=currentCount.getAndSet(1);currentRps=count;baselineRps=baselineRps*.90+count*.10;if(count>=cfg.surgeAbsoluteRps()||count>Math.max(10,baselineRps*cfg.surgeMultiplier()))surgeUntil=System.currentTimeMillis()+cfg.surgeDuration().toMillis();}}
 private static void trim(ArrayDeque<Long>q,long min){while(!q.isEmpty()&&q.peekFirst()<min)q.removeFirst();}private static String normalize(String ip){return ip==null||ip.isBlank()?"0.0.0.0":ip.trim();}
 public PluginStats stats(){return new PluginStats(total.sum(),allowed.sum(),denied.sum(),blacklisted.sum(),rate.sum(),quota.sum(),surgeDenied.sum(),System.currentTimeMillis()<surgeUntil,currentRps,baselineRps);}
 public synchronized void reload(){Config n=Config.load(configPath);JsonAuditLogger old=logger;cfg=n;policy=new IpPolicy(n);logger=new JsonAuditLogger(n.logFile());old.close();}
 public void close(){logger.close();}
}
